#!/bin/bash
echo "enter first number"
read a
echo "enter second number"
read b
echo "enter third number"
read c
if [$a -gt $b ] && [ $a -gt $c ]
then 
  echo "the greatest number is:" $a
elif [$b -gt $a ] && [$b -gt $c ]
then 
   echo "the greatest number is:" $b
else
   echo "the greatest number is:" $c
fi
  
